default: &default
  adapter: mysql2
  encoding: utf8
  wait_timeout: 300
  username: wizard
  password: test1234
  socket: /tmp/mysql.sock

development:
  <<: *default
  host: 127.0.0.1
  database: wizard
  wait_timeout: 1000000
